export default [
  {
    name: "soul",
    rank: "1",
    igl: "Mortal",
    player1: "Mortal",
    player2: "Akshat",
    player3: "Omega",
    player4: "viper",
    Email: "teamsoul@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/Team_Soul.png",
  },
  {
    name: "8-bit",
    rank: "2",
    igl: "Thug",
    player1: "Thug",
    player2: "madman",
    player3: "regaltos",
    player4: "surya",
    Email: "team8bit@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/8-bit.png",
  },
  {
    name: "SG",
    rank: "3",
    igl: "Seervi",
    player1: "Seervi",
    player2: "Shrydar",
    player3: "Paradox",
    player4: "Tedd",
    Email: "teamSG@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/sg.png",
  },
  {
    name: "OR",
    rank: "4",
    igl: "Anto",
    player1: "Anto",
    player2: "Jelly",
    player3: "Admino",
    player4: "Max",
    Email: "teamOR@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/or.png",
  },
  {
    name: "GODL",
    rank: "5",
    igl: "Ghatak",
    player1: "Ghatak",
    player2: "Jhonathan",
    player3: "Neyoo",
    player4: "Z-god",
    Email: "teamGODL@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/godl.png",
  },
  {
    name: "INSANE",
    rank: "6",
    igl: "Harsh",
    player1: "Harsh",
    player2: "Aadi",
    player3: "skipz",
    player4: "Darklod",
    Email: "teamti@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/team-insane.png",
  },
  {
    name: "TeamBlind",
    rank: "7",
    igl: "Jokerr",
    player1: "Jokerr",
    player2: "Manya",
    player3: "Nakul",
    player4: "Rony",
    Email: "teamBlind@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/team-blind.png",
  },
  {
    name: "TeamXSpark",
    rank: "8",
    igl: "ScoutOP",
    player1: "ScoutOP",
    player2: "Aditya",
    player3: "Pukar",
    player4: "Sarang",
    Email: "teamXSpark@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/team-xpark.png",
  },

  {
    name: "Big Brother Esport",
    rank: "9",
    igl: "EzePzee",
    player1: "Rishi",
    player2: "Saif",
    player3: "Sarvit",
    player4: "Uzumaki",
    Email: "teamBBE@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/BIG_BROTHER_ESPORTS.png",
  },
  {
    name: "CHEMIN ESPORTS",
    rank: "10",
    igl: "AFU",
    player1: "AFU",
    player2: "Kaalan",
    player3: "ShaDow",
    player4: "spyOP",
    Email: "teamce@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/chemin-esports.png",
  },
  {
    name: "Entity Gaming",
    rank: "11",
    igl: "Troye",
    player1: "Troye",
    player2: "Gamlaboy",
    player3: "Saumraj",
    player4: "Secrett",
    Email: "teameg@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/entity.png",
  },
  {
    name: "Global Esports",
    rank: "12",
    igl: "Darklord",
    player1: "Mavi",
    player2: "Noob",
    player3: "NinjaBoi",
    player4: "Shadow7",
    Email: "teamge@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/global-esport.png",
  },
  {
    name: "Team vitality",
    rank: "13",
    igl: "Neo",
    player1: "Neo",
    player2: "Nico",
    player3: "ClassifiedYT",
    player4: "mello",
    Email: "teamte@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/Vitality.png",
  },
  {
    name: "Velocity Gaming",
    rank: "14",
    igl: "A1mbot",
    player1: "A1mbot",
    player2: "IMMORTAL",
    player3: "Octavius",
    player4: "Punkkk",
    Email: "teamvg@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/velocity-gaming.png",
  },
  {
    name: "Team Tamilas",
    rank: "15",
    igl: "CarryOP",
    player1: "MantyOP",
    player2: "Maxy",
    player3: "Striker",
    player4: "Yuva",
    Email: "teamtt@gmail.com",
    Insta: "",
    Teamimage: "../../../public/images/Team_Tamilas.png",
  },
];
