export default [
  {
    id: 1,
    heading: "GODL",
    game: "BGMI",
    img: "../../../public/image/teamlogo.jpeg",
    player1: "../../../public/image/godl (1).jpeg",
    player2: "../../../public/image/godl (2).jpeg",
    player3: "../../../public/image/godl (3).jpeg",
    player4: "../../../public/image/godl (4).jpeg",
    p: "Godlike Esports is an Indian Esports Organization. It was formed in 2018 just after the first official pubg tournament was announced. It has an interesting story behind its name. There was a clan in mini militia with the name Godlike and when the game of pubg was launched, the members started playing under the same name Godl or Godlike. Team GODLIKE BGMI, owner, origin, roster, achievements, history, net worth The owner of Godlike Esports is Kronten aka Chetan Chandgude. He is a famous streamer and BGMI player. He was also a part of the first roster which entered a tournament as he himself was a PUBG player.",
    i: "https://www.instagram.com/godlike.in/",
    instaImage: "../../../public/image/insta.png",
  },
  {
    id: 2,
    heading: "Soul",
    game: "BGMI",
    img: "../../../public/image/soul logo.jpeg",
    player1: "../../../public/image/soul (1).jpeg",
    player2: "../../../public/image/soul (2).jpeg",
    player3: "../../../public/image/soul (3).jpeg",
    player4: "../../../public/image/soul (4).jpeg",
    p: "Team SouL has officially released the much-anticipated lineup. The roster features elite PUBG Mobile players who will now compete in Battlegrounds Mobile India. Team SouL quickly became one of the most popular teams in the Indian gaming community by dominating throughout the year in 2019. They won several tournaments, including PUBG Mobile India Series 2019 and the PUBG Mobile Club Open Spring Split 2019 India finals.Team SouL is powered by S8UL, a fusion of two large organisations - SouL and 8bit.",
    i: "https://www.instagram.com/soulesportsofficial/",
    instaImage: "../../../public/image/insta.png",
  },
  {
    id: 3,
    heading: "SGE",
    game: "BGMI",
    img: "../../../public/image/sg team.jpeg",
    player1: "../../../public/image/sg (1).jpeg",
    player2: "../../../public/image/sg (2).jpeg",
    player3: "../../../public/image/sg (3).jpeg",
    player4: "../../../public/image/sg (4).jpeg",
    i: "https://www.instagram.com/godlike.in/",
    p: "In a surprising turn of events, Singapore-based esports organization Skylightz Gaming has ceased BGMI operations in India. The news was made public by Saumraj, one of the players who was part of the organization's Battlegrounds Mobile India (BGMI) roster.",
    instaImage: "../../../public/image/insta.png",
  },
];
